# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ffce94b52782c81b1c80dafdee01e942b35f179951bab5752c82f8677b5930b3a020a022149810b039ff3a7363b09bcd419ad8630383d5e3fcf37b0c88b4bd7

test:
  secret_key_base: 2c8793e3caab4260640f3de2694ac5cf02164e9f96d1552998bf300bd74b81eb56b0c6f0eec013648997183e022c8f79d08a0b5b7883565528774f75bcbccf15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
